In [5]:
pip install numpy

     ---------------------------------------- 15.8/15.8 MB 7.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [7]:
t=np.array([0, 1, 2, 3, 4, 5, 6])
print(t)

[0 1 2 3 4 5 6]


In [8]:
print(t.ndim, t.shape)
print(t[0],t[1],t[-1])
t[0],t[1],t[-1] = 0.0, 1.0, 6.0
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])

1 (7,)
0 1 6
0 1 6
[2 3 4] [4 5]


In [9]:
t = np.array([[1, 2, 3], [4, 5, 6], [7,8,9], [10, 11, 12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
pip install torch

     -------------------------------------- 192.3/192.3 MB 5.2 MB/s eta 0:00:00
     ---------------------------------------- 5.7/5.7 MB 9.2 MB/s eta 0:00:00
     ---------------------------------------- 1.6/1.6 MB 6.2 MB/s eta 0:00:00
     -------------------------------------- 133.1/133.1 kB 4.0 MB/s eta 0:00:00
     -------------------------------------- 169.0/169.0 kB 5.1 MB/s eta 0:00:00
     ------------------------------------- 536.2/536.2 kB 11.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import torch

In [13]:
t= torch.FloatTensor([0, 1, 2, 3, 4, 5, 6,])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [16]:
print(t [0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[2:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([2., 3., 4., 5., 6.])


In [17]:
t= torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [19]:
print(t.dim(), t.size())

2 torch.Size([4, 3])


In [20]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1+ m2)

tensor([[5., 5.]])


In [21]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]]) # ->[[3,3]]
print(m1+ m2)

tensor([[4., 5.]])


In [22]:
m1 = torch.FloatTensor([[1, 2]]) #-> [[1,2], [1,2]]
m2 = torch.FloatTensor([[[3], [4]]]) # ->[[3,4], [3,4]]
print(m1+ m2)

tensor([[[4., 5.],
         [5., 6.]]])


In [23]:
m1 = torch.FloatTensor([[1, 2],[3, 4]]) #-> [[1,2], [1,2]]
m2 = torch.FloatTensor([[1], [2]]) # ->[[3,4], [3,4]]
print(m1.matmul(m2)) # 해열곱 연산
print(m1.shape, m2.shape)

tensor([[ 5.],
        [11.]])
torch.Size([2, 2]) torch.Size([2, 1])


In [24]:
print(m1 * m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [25]:
t= torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [26]:
t= torch.FloatTensor([[1, 2],[3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [27]:
print(t.mean(dim=0)) #(2,2) -> dim=0 -> 첫번쨰 차원

tensor([2., 3.])


In [28]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [29]:
t= torch.FloatTensor([[1, 2],[3, 4]])
print(t.sum())

tensor(10.)


In [30]:
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [31]:
print(t.max())
print(t.max(dim=0))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [32]:
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])

tensor([3., 4.])
tensor([1, 1])


In [33]:
t= np.array([[[0, 1, 2],
              [3,4,5]],
             [[6,7,8],
              [9,10,11]]])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [34]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [35]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape) # -1은 알아서 형태를 맞추라는 뜻

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [36]:
print(ft)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [37]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [38]:
ft=torch.FloatTensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [39]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [40]:
print(ft.unsqueeze(1))

tensor([[0.],
        [1.],
        [2.]])


In [43]:
lt=torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [44]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [45]:
bt=torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [46]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [47]:
x= torch.FloatTensor([[1,2],[3,4]])
y= torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [48]:
print(torch.cat([x,y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [50]:
x= torch.FloatTensor([1,4])
y= torch.FloatTensor([2,5])
z= torch.FloatTensor([3,6])
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [51]:
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [52]:
print(torch.zeros_like(x))
print(x.mul(2))

tensor([0., 0.])
tensor([2., 8.])


In [53]:
print(x)
x=x.mul(2)
print(x.mul_(2))

tensor([1., 4.])
tensor([ 4., 16.])
